### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by bkmgit** [nuclear868/mattermost-qt#5]
The file [COPYING.LESSER](https://github.com/nuclear868/mattermost-qt/blob/master/COPYING.LESSER) has LGPL-3.0 yet most of the the source files contain LGPL-2 or later, for example [main.cpp](https://github.com/nuclear868/mattermost-qt/blob/master/sources/main.cpp).  Maybe it is good to have the text for [LGPL 2](https://www.gnu.org/licenses/old-licenses/lgpl-2.0.html) in the repository or update the headers to use LGPL-3.0?

**Comment by nuclear868** [comment]
Thank you.
I fixed it just now. 
Updated the headers to use LGPL-3.0
